### ISSUE TITLE
etcd CNAMEs not stable

### ISSUE THREAD

**Issue by cybertron** [openshift-metalkube/coredns-mdns#8]
If nodes come up out of order (i.e. master-2 comes up before master-1), it is currently possible that the etcd-1 CNAME might point at master-2 until master-1 is available. Once master-1 comes up the CNAMEs will be mapped as expected, but it seems like this inconsistency could be a problem. One address might end up sending traffic to two different nodes depending on when the name is queried.

The reason for this is that the loop index is used to name the etcd-X CNAME instead of the actual number in the master-X name. We should probably change that so this works in a more intuitive way.

**Comment by celebdor** [comment]
What about adding an extra _workstation service with the cname on the masters /etc/avahi/services

**Comment by cybertron** [comment]
That could work. The only issue is we'd need to have logic on the host to figure out which address to bind it to. Apparently AVAHI doesn't support aliases, so you have to provide a full name->IP mapping to add extra names to a node.

**Comment by cybertron** [comment]
Fixed by #19
